//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class Names
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.Names, global::LightSwitchApplication.Names.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private Names() : base("LightSwitchApplication:Names")
        {
            global::LightSwitchApplication.Names.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static Names CreateInstance()
        {
            return new global::LightSwitchApplication.Names(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Names_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Names_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Names_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Names_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Names_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Names_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Names_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void Table1Items_SelectionChanged();

        partial void Table1Items_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Table1Items_Loaded(bool succeeded);

        /// <summary>
        /// Gets the Table1Items visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.Table1Item> Table1Items
        {
            get
            {
                return global::LightSwitchApplication.Names.DetailsClass.GetValue(this, global::LightSwitchApplication.Names.DetailsClass.PropertySetProperties.Table1Items);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Table1Items_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.Names, global::LightSwitchApplication.Names.DetailsClass, global::LightSwitchApplication.Names.DetailsClass.PropertySet, global::LightSwitchApplication.Names.DetailsClass.CommandSet, global::LightSwitchApplication.Names.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.Names.DetailsClass.PropertySetProperties.Table1Items;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.Names, global::LightSwitchApplication.Names.DetailsClass>.Entry
                __NamesEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.Names, global::LightSwitchApplication.Names.DetailsClass>.Entry(
                    global::LightSwitchApplication.Names.DetailsClass.__Names_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.Names.DetailsClass.__Names_InvokeSavingEvent,
                    global::LightSwitchApplication.Names.DetailsClass.__Names_InvokeSavedEvent,
                    global::LightSwitchApplication.Names.DetailsClass.__Names_InvokeClosingEvent,
                    global::LightSwitchApplication.Names.DetailsClass.__Names_InvokeCreated,
                    global::LightSwitchApplication.Names.DetailsClass.__Names_InvokeActivated,
                    global::LightSwitchApplication.Names.DetailsClass.__Names_InvokeSaveErrorEvent);
            private static void __Names_InvokeInitializeDataWorkspace(global::LightSwitchApplication.Names s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.Names_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __Names_InvokeSavingEvent(global::LightSwitchApplication.Names s)
            {
                bool handled = false;
                s.Names_Saving(ref handled);
                return handled;
            }
            private static void __Names_InvokeSavedEvent(global::LightSwitchApplication.Names s)
            {
                s.Names_Saved();
            }
            private static bool __Names_InvokeClosingEvent(global::LightSwitchApplication.Names s)
            {
                bool cancel = false;
                s.Names_Closing(ref cancel);
                return cancel;
            }
            private static void __Names_InvokeCreated(global::LightSwitchApplication.Names s)
            {
                s.Names_Created();
            }
            private static void __Names_InvokeActivated(global::LightSwitchApplication.Names s)
            {
                s.Names_Activated();
            }
            private static bool __Names_InvokeSaveErrorEvent(global::LightSwitchApplication.Names s, global::System.Exception ex)
            {
                bool handled = false;
                s.Names_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.Names.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.Names.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.Names.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable Table1ItemsQuery()
            {
                return this.Screen.DataWorkspace.ApplicationData.Table1Items;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.Names, global::LightSwitchApplication.Names.DetailsClass, global::LightSwitchApplication.Table1Item>.Data _Table1Items;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.Names, global::LightSwitchApplication.Names.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.Names, global::LightSwitchApplication.Names.DetailsClass, global::LightSwitchApplication.Table1Item> Table1Items
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.Names, global::LightSwitchApplication.Names.DetailsClass, global::LightSwitchApplication.Table1Item>)base.GetItem(global::LightSwitchApplication.Names.DetailsClass.PropertySetProperties.Table1Items);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.Names, global::LightSwitchApplication.Names.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.Names, global::LightSwitchApplication.Names.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.Names, global::LightSwitchApplication.Names.DetailsClass, global::LightSwitchApplication.Table1Item>.Entry
                    Table1Items = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.Names, global::LightSwitchApplication.Names.DetailsClass, global::LightSwitchApplication.Table1Item>.Entry(
                        "Table1Items",
                        global::LightSwitchApplication.Names.DetailsClass.PropertySetProperties._Table1Items_Stub,
                        global::LightSwitchApplication.Names.DetailsClass.PropertySetProperties._Table1Items_Validate,
                        global::LightSwitchApplication.Names.DetailsClass.PropertySetProperties._Table1Items_CreateQuery,
                        global::LightSwitchApplication.Names.DetailsClass.PropertySetProperties._Table1Items_SelectionChanged,
                        global::LightSwitchApplication.Names.DetailsClass.PropertySetProperties._Table1Items_OnCollectionChanged,
                        global::LightSwitchApplication.Names.DetailsClass.PropertySetProperties._Table1Items_OnLoaded);
                private static void _Table1Items_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Names.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.Names, global::LightSwitchApplication.Names.DetailsClass, global::LightSwitchApplication.Table1Item>.Data> c, global::LightSwitchApplication.Names.DetailsClass d, object sf)
                {
                    c(d, ref d._Table1Items, sf);
                }
                private static void _Table1Items_Validate(global::LightSwitchApplication.Names s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Table1Items_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _Table1Items_CreateQuery(global::LightSwitchApplication.Names.DetailsClass d, object[] args)
                {
                    return d.Table1ItemsQuery();
                }
                private static void _Table1Items_SelectionChanged(global::LightSwitchApplication.Names s)
                {
                    s.Table1Items_SelectionChanged();
                }
                private static void _Table1Items_OnCollectionChanged(global::LightSwitchApplication.Names s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.Table1Items_Changed(e);
                }
                private static void _Table1Items_OnLoaded(global::LightSwitchApplication.Names s, bool succeeded)
                {
                    s.Table1Items_Loaded(succeeded);
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {
            }
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class EditableTable1ItemsGrid
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.EditableTable1ItemsGrid, global::LightSwitchApplication.EditableTable1ItemsGrid.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private EditableTable1ItemsGrid() : base("LightSwitchApplication:EditableTable1ItemsGrid")
        {
            global::LightSwitchApplication.EditableTable1ItemsGrid.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static EditableTable1ItemsGrid CreateInstance()
        {
            return new global::LightSwitchApplication.EditableTable1ItemsGrid(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EditableTable1ItemsGrid_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EditableTable1ItemsGrid_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EditableTable1ItemsGrid_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EditableTable1ItemsGrid_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EditableTable1ItemsGrid_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EditableTable1ItemsGrid_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EditableTable1ItemsGrid_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void Table1Items_SelectionChanged();

        partial void Table1Items_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Table1Items_Loaded(bool succeeded);

        /// <summary>
        /// Gets the Table1Items visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.Table1Item> Table1Items
        {
            get
            {
                return global::LightSwitchApplication.EditableTable1ItemsGrid.DetailsClass.GetValue(this, global::LightSwitchApplication.EditableTable1ItemsGrid.DetailsClass.PropertySetProperties.Table1Items);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Table1Items_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.EditableTable1ItemsGrid, global::LightSwitchApplication.EditableTable1ItemsGrid.DetailsClass, global::LightSwitchApplication.EditableTable1ItemsGrid.DetailsClass.PropertySet, global::LightSwitchApplication.EditableTable1ItemsGrid.DetailsClass.CommandSet, global::LightSwitchApplication.EditableTable1ItemsGrid.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.EditableTable1ItemsGrid.DetailsClass.PropertySetProperties.Table1Items;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.EditableTable1ItemsGrid, global::LightSwitchApplication.EditableTable1ItemsGrid.DetailsClass>.Entry
                __EditableTable1ItemsGridEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.EditableTable1ItemsGrid, global::LightSwitchApplication.EditableTable1ItemsGrid.DetailsClass>.Entry(
                    global::LightSwitchApplication.EditableTable1ItemsGrid.DetailsClass.__EditableTable1ItemsGrid_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.EditableTable1ItemsGrid.DetailsClass.__EditableTable1ItemsGrid_InvokeSavingEvent,
                    global::LightSwitchApplication.EditableTable1ItemsGrid.DetailsClass.__EditableTable1ItemsGrid_InvokeSavedEvent,
                    global::LightSwitchApplication.EditableTable1ItemsGrid.DetailsClass.__EditableTable1ItemsGrid_InvokeClosingEvent,
                    global::LightSwitchApplication.EditableTable1ItemsGrid.DetailsClass.__EditableTable1ItemsGrid_InvokeCreated,
                    global::LightSwitchApplication.EditableTable1ItemsGrid.DetailsClass.__EditableTable1ItemsGrid_InvokeActivated,
                    global::LightSwitchApplication.EditableTable1ItemsGrid.DetailsClass.__EditableTable1ItemsGrid_InvokeSaveErrorEvent);
            private static void __EditableTable1ItemsGrid_InvokeInitializeDataWorkspace(global::LightSwitchApplication.EditableTable1ItemsGrid s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.EditableTable1ItemsGrid_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __EditableTable1ItemsGrid_InvokeSavingEvent(global::LightSwitchApplication.EditableTable1ItemsGrid s)
            {
                bool handled = false;
                s.EditableTable1ItemsGrid_Saving(ref handled);
                return handled;
            }
            private static void __EditableTable1ItemsGrid_InvokeSavedEvent(global::LightSwitchApplication.EditableTable1ItemsGrid s)
            {
                s.EditableTable1ItemsGrid_Saved();
            }
            private static bool __EditableTable1ItemsGrid_InvokeClosingEvent(global::LightSwitchApplication.EditableTable1ItemsGrid s)
            {
                bool cancel = false;
                s.EditableTable1ItemsGrid_Closing(ref cancel);
                return cancel;
            }
            private static void __EditableTable1ItemsGrid_InvokeCreated(global::LightSwitchApplication.EditableTable1ItemsGrid s)
            {
                s.EditableTable1ItemsGrid_Created();
            }
            private static void __EditableTable1ItemsGrid_InvokeActivated(global::LightSwitchApplication.EditableTable1ItemsGrid s)
            {
                s.EditableTable1ItemsGrid_Activated();
            }
            private static bool __EditableTable1ItemsGrid_InvokeSaveErrorEvent(global::LightSwitchApplication.EditableTable1ItemsGrid s, global::System.Exception ex)
            {
                bool handled = false;
                s.EditableTable1ItemsGrid_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.EditableTable1ItemsGrid.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.EditableTable1ItemsGrid.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.EditableTable1ItemsGrid.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable Table1ItemsQuery()
            {
                return this.Screen.DataWorkspace.ApplicationData.Table1Items;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableTable1ItemsGrid, global::LightSwitchApplication.EditableTable1ItemsGrid.DetailsClass, global::LightSwitchApplication.Table1Item>.Data _Table1Items;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.EditableTable1ItemsGrid, global::LightSwitchApplication.EditableTable1ItemsGrid.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableTable1ItemsGrid, global::LightSwitchApplication.EditableTable1ItemsGrid.DetailsClass, global::LightSwitchApplication.Table1Item> Table1Items
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableTable1ItemsGrid, global::LightSwitchApplication.EditableTable1ItemsGrid.DetailsClass, global::LightSwitchApplication.Table1Item>)base.GetItem(global::LightSwitchApplication.EditableTable1ItemsGrid.DetailsClass.PropertySetProperties.Table1Items);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.EditableTable1ItemsGrid, global::LightSwitchApplication.EditableTable1ItemsGrid.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.EditableTable1ItemsGrid, global::LightSwitchApplication.EditableTable1ItemsGrid.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableTable1ItemsGrid, global::LightSwitchApplication.EditableTable1ItemsGrid.DetailsClass, global::LightSwitchApplication.Table1Item>.Entry
                    Table1Items = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableTable1ItemsGrid, global::LightSwitchApplication.EditableTable1ItemsGrid.DetailsClass, global::LightSwitchApplication.Table1Item>.Entry(
                        "Table1Items",
                        global::LightSwitchApplication.EditableTable1ItemsGrid.DetailsClass.PropertySetProperties._Table1Items_Stub,
                        global::LightSwitchApplication.EditableTable1ItemsGrid.DetailsClass.PropertySetProperties._Table1Items_Validate,
                        global::LightSwitchApplication.EditableTable1ItemsGrid.DetailsClass.PropertySetProperties._Table1Items_CreateQuery,
                        global::LightSwitchApplication.EditableTable1ItemsGrid.DetailsClass.PropertySetProperties._Table1Items_SelectionChanged,
                        global::LightSwitchApplication.EditableTable1ItemsGrid.DetailsClass.PropertySetProperties._Table1Items_OnCollectionChanged,
                        global::LightSwitchApplication.EditableTable1ItemsGrid.DetailsClass.PropertySetProperties._Table1Items_OnLoaded);
                private static void _Table1Items_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EditableTable1ItemsGrid.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableTable1ItemsGrid, global::LightSwitchApplication.EditableTable1ItemsGrid.DetailsClass, global::LightSwitchApplication.Table1Item>.Data> c, global::LightSwitchApplication.EditableTable1ItemsGrid.DetailsClass d, object sf)
                {
                    c(d, ref d._Table1Items, sf);
                }
                private static void _Table1Items_Validate(global::LightSwitchApplication.EditableTable1ItemsGrid s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Table1Items_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _Table1Items_CreateQuery(global::LightSwitchApplication.EditableTable1ItemsGrid.DetailsClass d, object[] args)
                {
                    return d.Table1ItemsQuery();
                }
                private static void _Table1Items_SelectionChanged(global::LightSwitchApplication.EditableTable1ItemsGrid s)
                {
                    s.Table1Items_SelectionChanged();
                }
                private static void _Table1Items_OnCollectionChanged(global::LightSwitchApplication.EditableTable1ItemsGrid s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.Table1Items_Changed(e);
                }
                private static void _Table1Items_OnLoaded(global::LightSwitchApplication.EditableTable1ItemsGrid s, bool succeeded)
                {
                    s.Table1Items_Loaded(succeeded);
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {
            }
        }
    }
}
